const output = document.getElementById('output');

var sum = 0;

const priorities = {
	"a":1,
	"b":2,
	"c":3,
	"d":4,
	"e":5,
	"f":6,
	"g":7,
	"h":8,
	"i":9,
	"j":10,
	"k":11,
	"l":12,
	"m":13,
	"n":14,
	"o":15,
	"p":16,
	"q":17,
	"r":18,
	"s":19,
	"t":20,
	"u":21,
	"v":22,
	"w":23,
	"x":24,
	"y":25,
	"z":26,
	"A":27,
	"B":28,
	"C":29,
	"D":30,
	"E":31,
	"F":32,
	"G":33,
	"H":34,
	"I":35,
	"J":36,
	"K":37,
	"L":38,
	"M":39,
	"N":40,
	"O":41,
	"P":42,
	"Q":43,
	"R":44,
	"S":45,
	"T":46,
	"U":47,
	"V":48,
	"W":49,
	"X":50,
	"Y":51,
	"Z":52,
}

const input = [
"JppMDcJPcQbqGqFb",
"ZStgnHtsSjGBhqFbBmsm",
"djzzwgHHggdnfwjtMPDPMGpPlNfpLDll",
"dRCtwtlCSttPtlNPNtgvPrDqmBsjGSpjBBsJsqqmrp",
"ZhWnZhzMMfnWWTDzBrmsmjsBccJB",
"TFQMrZrMfZrLZZnLQdlvNdCgdHPlCllHNF",
"PVddPnZWDDPqmHZzqVPzqdHdMRMJjQtvmvjvtTQQtlRtbbQl",
"fsNswFpChpNwfgtMvCbjTRJBbtRj",
"SFgfSMShLcsLgNMFhpwShFFZPHqZGZPqHdzPZHZcdzDDqd",
"dHffzCqSfJCCzCPvdcpzRrBDDBSBBBMtthDDrFMT",
"bVsZbsrgbWshBTFtDTtZTD",
"slWGNbNWgWwnmNnwgnlGjdJJdPHcvcrcHjqPzdqPvp",
"vBFBzGvGBvjFpGWcvCCvBvGPPhZbgLhMnhrPgFgPFgLLPF",
"dVlslfdJNVJJmQQwdNRNwLZZZrrqhbPbZndpdgMhLP",
"HJRHJpNJlVmftHfNQNRsHmmGCtGWjGDDTvCzcjWDStvcvT",
"cVQzCCCpVVjgHsNwwFRqSRSRRtNH",
"PWfhfPhbWWdWllPDdTvdbnvhLJLLMJFTSNwJtMRwJLqJJNMq",
"DnfblllPbDrbWmbdPFdvlhdgQzzZZzQgcpcsZGcGQQgcpr",
"hdFnnrdLnJRrZMzVlMbrwZvz",
"TgfjGCcfsqfqqBfRMPDVvVVvTZRPbP",
"qQqffcGStBSCQcsqCCBRjGqWhHFptFdnhNLmhnLWmphLLt",
"WHPqWhLWHBMqddCdtDRwStDSwgnw",
"rfCfZTmvpvvpFVfFrbvTbvcgtwgtStntggwbSJttgJtwgw",
"fpQFsmfFmfZcrFCMhWNQWLCzhhCM",
"zdqqJHDWwqNNZjQSmtdjpmfnjj",
"GFBcPfBLPThcTcLRbpTQQjpTQrjSnQjlvn",
"MFVLcsPVbPcRGfVPFRgDzJsHZNDCZNCNZsHg",
"WQdMhlmQMwfZlQdgdHfddvtzmbJbcsctbBJqqcvqzB",
"rSTrDDCSSGRCnnSGwwzJsbBvJsCCttccsvsz",
"VnFwDrNwPwVSDrLgjfZZdMQFMWgljQ",
"rJNjBLNQjvLQjFFLQJCFTvGWlRRgfGWDWlCDzlGnRRWG",
"tMMhShhwhbgplflwDlnnnzDH",
"ZcSZVMSqshhQBQqQvqQgjJ",
"btTtWGbvtcvHHccdNRhHdl",
"TDzqLPSqBzqVSldPddHhhNNlRQ",
"jBLDqDgZZBzJJmsbWjppmmpTWw",
"LLDTRRfTwZRGZfDCRTwRsVHsVFBVZVlmVFBFlFJl",
"QjWpQrzQcbhfMqrVVHVPFslFVpVmHH",
"hqhzqMfNvjvMMzhdRDdCwGDSSdnvRn",
"jmMdNCLjLmJPtHtSHhSVVJ",
"pDBqgBgCvbfGBBbCGHZhtQZtPHVSVHPV",
"pBnWgBpzWzBbWDWvzwpgCvqcmLNTrdLmmrnRLTrmrTdmLd",
"dRWWtRGBDPQctQDZ",
"CMfnCfFMmTTFVCmfmTLvsnMPZjccHRcPrRPsZQQZPQDRrQ",
"fLCffmRTCvRnmTllzVvpdpphNJggpGbJJJpdlh",
"cfsfbbWqqZqDScbhGDPDjTPmpVtmmPjPntFD",
"dCBBCRQCHNHLMQvrJJJBJLrGPMnjVtPjVMmnjPFmPmMpFn",
"HvRGLddgHHvqhwzbWhcgcf",
"DHmhhDDhbqrRhvbrHqhPbPvBwwWwTmMGTVwwBMGWVNNwVw",
"gSzJjnnjsscfcsZcSfWwQGdMMcWTBcTTMTMw",
"nsFCCFZsnSlCFBFflfflsztRPCqvvHPttRbHbhvPrrRr",
"SGNRLzpNpgNSNNlWFNwzqJfHfJHBtBdJhBJrHd",
"bQnjPTnjVdZtPPrfLP",
"TTnTccLnjGFcDNggFl",
"lBJmNzJlzmmQBlzgVVjLWRDfLjRsRLWWRS",
"vTMvTvtrfdhrrrPTdZwTTwtDqSSnWFWDFMMsRssjjsRqWD",
"ZpbvHbZddtbrdrdhcBmmpGQfBQgJNcmz",
"qsmhTmTVcDdcffhPhPvvzFhF",
"BNNlJbjWBWjtRtNljbmBBCpFzPlFPgpPfwFnlffnlPgg",
"JtBmmrrrRbDSrVqDqVSD",
"VmSgpSLgJjVDMrFrmMlfFmsG",
"bZWhZbzWcCwTWPRCwwwSPQzwMHnflHnGsMGnTrsflGMnlfTF",
"CqWhWqWCCWRRZQcLqDLpVDDLNStpgD",
"JwzTVzzcLzVJVVlJpVTwzGcrWhFjqsBjCjQFjWcCCjCjBF",
"MDSNQMtbSSnSbgbRDvnRNgvhmrqrjBCBtmCrCCWFqthhWm",
"bgMfNSSNZTwZQddGJZ",
"jjPgbFjjStjjPcSbrbtpvNrGnGDvBnMGvNDNGG",
"LwdZwsTdWTTmwDNCNppGBsnpBR",
"mWmHwZWhTTJWHBdQQWBjcFczSgjlSftjbtQPzg",
"fCBlrffzlCzcmfLDlfgRRnHScsHvRSQHMQvs",
"LthpZqtpVThZhGJtqTFvHsVnvsvMsggjHQjgQH",
"ZWFWGTLTWBNCWfDfmD",
"BpFqJrpcZZBDhDsNqMHhRG",
"zwlzPdmzPLhwvhMgsHnN",
"mPlWjlQfQjjllWtjQCWzCrBFJFTBcSNcJbbZfcZJSb",
"FpzNFTThBDChnnzNBCBNDzWGndgWqbJWVGqmPbJqQgQm",
"HQRctcvwgddVcJGd",
"LwRMZLjQfSRjFNzFSrhNsThS",
"WgRWVLWhFqgqgcgWHqLRWHVRbbbNwBmtBcNcwdwwBNwBzwBN",
"pSfssjDSrSvJpNJCztbJBtMNbt",
"TzsvGGnjGPsPjSTpDrPfPDSHhWqLgZZVHVhZZZZVQQFLnZ",
"sHjtPjQTtDbsfrrqWR",
"ZmccchvlvSvvZNMVNhvBLWRJJblWJWJlJfwHbwlL",
"hMMBzSMppVSzSNNmNgHjPgGPFTCpTTgTgG",
"rPQpCPPCQQZdcFhcZgzVJgwt",
"vDBSHmvHSSMlDWWmljnHBvFwzzcrwhVSJwVFtzcJJghw",
"bmmrsrsbsvNdCTdbPTdb",
"NgzBnsBNnfjgNvvfvWbtShSSFSMLJMFjjbPh",
"CCcRHdlQrQPLTJPLGP",
"HrDlRcqcDJCCDJHlcplrDJDfgfzBWWNZfvsnNqWwngZWwW",
"TggFVbjVTVzRwFFjjqBBqpzNztqcQqNNqN",
"SnZPrWndmShSZSPsnSLsJhpMQpcJtNqBClltqctC",
"mfWsGdnZZWmZmrLSfsrnmPggwtggRgGTVHvRwgFDjTGT",
"wQMZFQwppbPHPbLQJsgQNJJmBnds",
"qrSGvRRCvTzTDNnhNgmCgdBm",
"qzRrcRlGjvvzlzrvjcGqSSzMHWwVdPMWFpFMHMHWlPWMVV",
"BccsFzrBcsfpccccgFmQqlGNqCTLTlQnqgLlRG",
"MZbVSMddddSPPtdHPVJPJdTllqLNLGGTNCCRhTnHTQHh",
"DMwtbVZDZbSbpprcpccppwrq",
"bSZTdNqFjjzjqQMQ",
"WtRztLsWJpPLzrsMDlDQjMhVMC",
"pcgHRpHmWPJgLRzBJHBPPRBfvvfGNGvvFwfvSvfTmNNZfN",
"RjvBljWTTWTlqmBvHjGptRgccZcbPtcttbpzbn",
"VhDSDdJLJpSNNVVznPzzzSzcZFngZt",
"LsMdQNVMHsBHjqps",
"rSPSLTnSCClfSFCR",
"MwtZgwNBzzTjzZMbbmjNtwmBcRvFqQllqtQRlFRVqRqVVcvq",
"TsMhZsjNjBbTbBbwZLpDnHdDGdHWnpGHnh",
"LfdssTFBjFHSwlhzCcZZgMMfMhZZ",
"DmtDvrpmNStVvqpPczrZMMhZhhChCC",
"vJtJpQWvNVDtJFbHlJSlBbSF",
"PgvHLbcgRcGGHzRvgGgchBzsCZnmNZmZddrCrvdddZCZrF",
"JQBMjlStJrQsZFrNCZ",
"JSJTlqMtjptlplSSqJVDBqphwhhwHRPRggGbGzHbgzVRPH",
"pBsztsZdBsnWhntVnhtVTqTWNQlGGTGGFFlQFlTl",
"fDvLSMcbDbfMrGqFqSGwSQPzqz",
"zjcvLMMvffLjgggzfjjJCCLcdBtRphddBmmZBpCZZpZpmmhs",
"gmmSDplcPHDfHDlbVNrtCtCCNqHvTn",
"QGwJjzdPMzJhFLwnbvMqrTVCCMnvMv",
"LQQZdGjGdJhFBFQGjLGBJzzsBSWcPflllcfmDmfBsmBWPs",
"sMppbLDRMQbrTDTJjwcqnfnjwwnw",
"CgmFgSPHPzHgdmJWZZFzCzZZcVnGGnttWtVVVnccfjVqwVff",
"PhCChPSNgPgPJhPHhFZgsDNRspsvMNQLRvNDvpbD",
"pHnVnlRGVpfgpfgCpCTz",
"LCNQPqZCqNSSZCStzPgTmztwPfzwzT",
"dbSqhjhqQhNLQLFjLjGvFcRnCcsvRVvvsFnG",
"QTdnDTDQbCnMdbqdwSmJBljFJZhttJZMSh",
"HfNfLNzGLsgWBpGJthlZFBSB",
"ssRPHPfNsWHzZZvrvHfgLzNwnbbVVRwwRbVVcqDTddCVdD",
"ZhZBrJssjrNsbRtWpjwjlmlm",
"qTfHzGTfTGqqLGMdCCRcmmRRZcbPMccWmcRw",
"dVCZdDHdGHQhBVNJSsBhBF",
"NsplbGDbblHcbCpDlDGDPlPpJjdrVjgrvHnghvVdJrJdvvdn",
"tQFMZNWSmWFQRzQSwtzFmwFFJdVBghVrnBjVjBgrvVjMvrhJ",
"FFRmFZZRzQRmFLQSZZWQWFCPCNGcTCpGpfGfLTpblpff",
"dnhQHqQCnqWwNQCwCRRdJjjJVVPmVVJsJP",
"LccFRDgfMgLFBJVlmVVmgjrPzZ",
"pvfGpRpSpTnTQbvbTv",
"nwNlWwhWwNmJvQQdzdzZGMqDzn",
"rcVscPfrLcfvjTFcQDqGdZqMzMSHZHjS",
"LsfbbFcvVgRRblJRNR",
"Rmrrlmltcffhllfl",
"DDZMMMFZVsFsWZDSHhPPfgQbPPnQgcHctf",
"zGMGSBVDWCrvwjtBvm",
"DCZHwdDwNNGNZDZCjjtpTHLvtlgLbRLttlTL",
"BzPzBJffJJQgLlRgGztQ",
"PJffcJhJfNNSwFhGZC",
"blplfHbwZSfbcbwSbfVSHDHcNvdrvrWsCrvWVCRWnvNndtWW",
"hQzBTQLLMBWBsnsnNC",
"zMsgTjqTqPpZHbfp",
"ZLNNLtfZhRJQtpQhNRttZRqcGFcqGBzjrcqclGScFljjcj",
"VnvVVPMWHwgJCMvwdcGFdFrGcwzGBG",
"WHgPJJvWVTgnvgvTHmWCHmsNZRtNRDZpfZQffZZssR",
"rZgMFMVVjGbVSqZbhftLRDmCGRCNDCtm",
"cdddQzdWsWnQvzscnfRHmfnDNtLNChRmfH",
"zplDQdDzwszlDsWdPcldzMFFrFrBFgpqVBZgSgZFrF",
"gbzfbTvbJgbvzvTvJvJmzvjcBBQSfWDLCSBQQfLZWSCdBHHD",
"GhnMhsGrMNPPwnwsRPNsFCZDWHZdWBWHdrZLdCHBBC",
"PsnGsssGNsNRFsLGwMVNccJVmbjcjJblbzTVjlTz",
"RfBqNfVmPLTTTVRZMMBWjlMvBgbbMs",
"rHJzDwJdHzQgbMQlWMhd",
"HtJrpCcHflLPFfpq",
"SSGtmjQFStDbQbqGWJNnpZwgPsZjnJNNfZ",
"RdClRMhlldHdlvdThNgwfJNRspNwJpwZcN",
"CMBLgvvBLhrrBHTCVVLBQrWtbrDGmbtWGtzDQFGb",
"ZRRCqHpRdztLSqWz",
"hRsGjMVccGshPVDVcBmfgFFzggFgfBmWWtSd",
"PVjlGhcGJjGPsGMjjDVrMTpRnvRZlHnZNNQbHppTTC",
"QjbjWWlndRbwwwQWQdtpTVVZtzRPhHDzThhP",
"fFfLsvrLCrmvGlSfLSrlPHThDzTztHVtzDzGtTVh",
"fvrgsfccFLLLSvfMCCSWBjdMqdqNWBdBQNnWld",
"pjGPvvbllvqGvGjwMbpbRmgSmSwtRtShgSSWWQmW",
"DffTZLLzFFFTCRJMhWBzhmhgJt",
"CVVZLLTTsZTFCnMffMTFHffLVpGpNqGjNbNPljqVPcGNGlcv",
"rvJfztqQJqqrqHHwCzClTbBhDBBDrbSgphbVTrrV",
"FFGdNWFLGWMmLDbpRwVbgRBp",
"dmNGmZjMjQwtHCCw",
"MSGbqbqMbbGDhSSGDhLNBPNcrDPPfzfczPfrnv",
"rRwsrljslRgslwwgpssCjRtBNvnmPmBmccvmPnmzcP",
"CjVjsssJQpTCrCCgHJLMSZbhMhWGZhHG",
"JtBGBFGRVGVLLctRttthLFRBDQlDppljJwNQlpHHQqDHbHHN",
"szSZTrzdzTSMdzsmsqqQqwdbgDNqgQNjlN",
"SzmrlWPrlfPMsMZTPtCVCFRhhvhccLFPvL",
"chmbsMDMMcBnGbZBzZGL",
"JjjgJrJJggNgtrQSQBLjWBZlGnnB",
"rFNrFtFCRNVrrsHmMDcsLqMhMF",
"DLMwrBGgrBBDrcBcNBgWhpGhqVhhqSjqqqmjjp",
"JfJCZCdtlbZlHHbjWVpPmHWb",
"lTtZtnFQCztWFzJflZLcsrLFNDRNBcswcLMM",
"tsVttVCBsCcCqPqwvtqNPQjWDDWjzQQWnpJQSrWJJN",
"LMRdZvHGgMmZZGGLGLbhLhJpjWrSjndWJpSJrJppJnpj",
"RhRgLMlmgMGMFGLlTtcBvwcfFCtVvfFT",
"llBBmtncBglfqwsdwsjdbHwQHm",
"zGRhPJvFzhvFvMDGFvGPwSWWQpdpHSwSjWjHsWMw",
"JGFhDPrLTzhLhvFPzPjLjTzFlBqltnCqqBffcTgfnZfCfCnB",
"QWQGNHQBffCNDMPdRTDLPVMN",
"hrtlhtzZwJtwwgFgtlJthJJtZMqPVVpLmDVqRDmVPmMPVRTV",
"SJSSnJwJlsFFvcHSBbfLQHGL",
"zMNVzhNFsdNssmhlvtQvlttBlVGbTt",
"wHpFwjHjLFHlwtncTQlnwn",
"CCpjpqLCLqJggghqRmFsNRFmPszh",
"CTjmprmNcnmCNVQbstnstvbnQv",
"jqqdGhHgPRdfRRQvfLQffz",
"BGgqBhMdgqBHMDDqqMPwgdhSTJNjjmJWWCTCCmwTWZNpmZ",
"LqSDFFmdqDBDbbBHWl",
"dQcRpgwRQPngBWHbVWht",
"vdQMJQCQQvrJNqrTNsSZSmZT",
"cqrHcHHFNFPLLNPHLWnHHFHFjvlbZfWjSjBjZfSblhbBSbSf",
"VdVTGwTzTwTpMJslvjfsbbZSvnBClj",
"nJdGmmTpTTdmNQNNLPPmDFQL",
"VcjpTTtpcbThJBTTcjBvSPJzJlvPlwfJrgrgvw",
"dmshCNqnqdhmRsCsqCnrNgPPrPfzrNLfSwSgzl",
"ddQZdFnhsMttFTbDDD",
"hLThMTSdfMzzLzTLsFTbwtDvtsFTnttF",
"pZlNllPWrPCQPQlWNqjrqrjsnfDFbbtbstwswtvDnwtwjt",
"pCNNQBCClQrplrfHQpQdSRMSVRhJzRchRhGHSh",
"RZfVfRnTcPQWZcRVcRNSvljQsSSjNvvNqvss",
"pwbwgmqJhGlNvvzgMM",
"pthrhpmthmwhHHpLbbdrJmLWWRPTRZnCnPCPBnWTWTZq",
"nzsJJsMjGMMsQFbnNmLnmCfb",
"HlllPPTPlWTPDRRDRHcwwhrLLZfQmgmmQCFHvNZCgfggZQ",
"lPcNTwNWddGsMSttdjzj",
"bTbJZJDVFdqpBZTFTZJprdcsjjGszmjQszcjzDvsgccv",
"HHLnhMNCCPhfhCLMlPlnvgGfctscSvtSjGjztQtm",
"wWNQMPPMwlPHHPnnRLwWpJbrbbqbdppqJVJdZV",
"gpgpNnnrhwBVWFqgjqqF",
"ZCTsdRbCGZpZzCSGbWmtMBmWtqBBqdjjmq",
"LcsTSlplZrJNcQQPvH",
"DJDpMcqJDcDddNcJPGcJGFfnfZZmZZfRQZRNmVQVnBNn",
"WWThvSSHFshlSsHvgTHLlzBQfVWwmwnnfmRQWnQVRn",
"vljlgHjhstHbLhjLjrbPqMGJcJFJCMPrdF",
"pJlPMpMBrrMcnrBBMMrvdhdgFvmcFdWtmdtftg",
"bVVRmTRVTVVSVVVzZZqsggFHWTWtWffWFfWdtHdH",
"RjLQDSzmVsjRRZSZQrCMJDPwlnJJnGGrPB",
"GRgJtglPGlCrhQQrfW",
"vSjvZvZHNBjZSvwjvmvNDqhhFqhHrMhrHpfWqQfhpW",
"NBmwDSbZbvsNNBjmZfJzJgbVnGJbzVzPVRtL",
"QQZVQCdlVmdZnWmJBrLwSJRdggwdJr",
"DqHhPhcpvDqPFjhHjtFPssSJNfSBwBvffrgJwwJLBJbr",
"jpsHcptHsqtPttsjctpFhGlZwCMlWMmWGCWVQnTMVWmz",
"zzvnHjHWSfnvzpnfSRHdgrrsmWmhVrrwwbTrTmsrwm",
"NlLNGqqclqlZZCLCGGCPllJhhPJbrmpmrwVshFVsJbwr",
"DMLDNCZQCGLQGDtQpGtMjRdfdSRSSBtjtBjfjgjS",
"WBBJfjBQJjftGCbttVJptC",
"sdlmTHsqNsqpRtGcbWdbnR",
"svNMhmWHNmvmvHZWTvBQDgSSjDFPSBSFPP",
"mrlgqncgwHdqWWhRNtRttSvbRwwSvN",
"jZLCZVZzVcCTcpCDVSBBSbvvRFbfDBSDNS",
"VPJVpQjTZLjVLJJQGZTZGcQVghsGlmhshlqnghqrdrgldhlW",
"qwGDMqMFWbFbqbDwMgqgnjfnffffcTTjNnpTfBncZZ",
"lSdclSltlzPsJlhNNfTQPTmQhpPh",
"LtllsscLLLvvJlSzWGqwrDGqvbqMwMGb",
"bnfvnnQsVTdHQDmdNN",
"fwlttwrfSfLwdGZGmGND",
"qlPrjjplfSpjSltfttBBsvgzgbgnggBqWVvC",
"HHrBSmBqBHdHCFcQsc",
"WqtMDDnMMZhMhcsQVM",
"bqtbGDLLTTnRPwvGgBNmNrwvjm",
"RwWzWFwBcdSdMgJW",
"mrTjVQDQthQvjrvTmggFbbdgSJcJDFgSdg",
"phhFtvjNvFvTTvmTHZzlGlzZRZLBlzRp",
"cHlZmZmJSHZcTVGmvZVcGVHlNtbDNbtWFWdtlbCWbWtQDFdr",
"pwfwgRhngPjjtdWdNtFrdFwT",
"RTgMpfhBcMJGHqcz",
"dmCbpCLQVFmCRddCTFLCgZtWPNBhSNNwZWgWZvSwhN",
"rDzGDjJHhhwzThBS",
"rJrclsjjsJMJnJMLnbQQQFmRTqLVRT",
"TgFTGPtrWHzgCJDz",
"fQbfLwbbFbWjHJHWjd",
"LvQvwVfQvQhLLLLsmMBfLfBhqchtGFSNSFNqrSqPcqSGttSN",
"MsMmFgTVMMgMdFVMhdzWqCCBCWjWqBWqhzzL",
"nHfZDlbvcrDpcpcfDJbNJqGLbCjBmjLzJC",
"RnDZHwmmTwVMTsMS",
"NpdpdnjNCRjBnHRPpBDnhSdSwFFLFdScFFWcFWLd",
"stqMrMZtsQMJmMqvrtqMbstQVchPFWgFVVFVwfWJcSSWVSSV",
"MQrZzbvMrrrZZtZmstMtMsDRRjPHCGTjBnzpnDHTCGjG",
"ClGGvDMGMNhNSmFVPbpgFgmFgZPb",
"WhTTLWsBBWTcrPpggtQpsQFpVb",
"fBRTqWLjTrzDNhMvCSGDzl",
"jbzjttVzpbWzWVbTtzWzVwPbPPcwDDccccFNFLMFsm",
"rlghJZHmCHvHJvRLSNLhhhccNPwcMP",
"QffmBZRBGtVTBdTG",
"bDRqHwwRpNPnbppn",
"FqrlQSQJSVsQrSCmpdPNpcNCcP",
"jFZjrssjBhrZVhJLLGHfMHfwtqRjMqRTvD",
"SMMCTBzFfSRhTThCSMRSzzHnJgqGDHQgGVDnqrqnqqnqcQ",
"ljvjpWPbrWWtrbmDVDlmnDnqVmgJ",
"bNjsNPrNPtswfZzfTSTBwhSM",
"hNMNdssdMqdTQchqgNZzHtwmwGHHzmQZGHDH",
"JrbJvJrvLrPjrPCVCjRBLPbzfRFZmzwHgFHmGHmwFwzFZR",
"rpbrvVjPCBbCJrCSLSPsTlphNncMglcNTMWMql",
"fGWGHbrllCCWWllFNPQSZvdPSvdZTffZ",
"tqssVjJMJWzWVvSvWS",
"qtwMwDWjnRRwssWjngwjjnhhDcCLhhCFHlcmcbCHFmDC",
"rFTdFjdRDTTlDWCqvhwLhwZdLS",
"QzfJfnfsbsJHMnNmHhVpCZwSQSWqSqVQhS",
"nJnczsHzNMmBJnbnbNwnfzJfcDTltllRTgPlFlgPrTDjPRGl",
"ZLCGDvvJlvGChSPZWPSsZWdRRN",
"rQccBwcccnHmQggnVLPLWpgVWPpWzSRs",
"fmwTfTHnMBTfJDbfftJLvhlL"
];

// const input = [
// "vJrwpWtwJgWrhcsFMMfFFhFp",
// "jqHRNqRjqzjGDLGLrsFMfFZSrLrFZsSL",
// "PmmdzqPrVvPwwTWBwg"
// ]

function CompareArrays(a1, a2) {
	for (i in a1) {
		for (j in a2) {
			if (a1[i] == a2[j]) return a1[i];
		}
	}
}

function CompareGroup(a1, a2, a3) {
	let sameLetters = [];
	// compare two arrays
	for (i in a1) {
		for (j in a2) {
			if (a1[i] == a2[j]) sameLetters.push(a1[i]);
		}
	}
	// compare result with third
	for (k in sameLetters) {
		for (l in a3) {
			if (sameLetters[k] == a3[l]) return sameLetters[k];
		}
	}
}

// part 1
function SplitInput() {
	for (i in input) {
		let length = input[i].length;
		let half = Math.round(length/2);
		let left = [];
		for (let j = 0; j < half; j++) {
			let letter = input[i][j];
			left.push(letter);
		}
		let right = [];
		for (let j = half; j < length; j++) {
			let letter = input[i][j];
			right.push(letter);
		}
		let sameLetter = CompareArrays(left, right);
		
		sum += priorities[sameLetter];
	}
}

// SplitInput();

// part 2
function FindCommonInGroup() {
	for (let i = 0; i < input.length; i += 3) {
		let sameLetter = CompareGroup(input[i],input[i+1],input[i+2]);
		sum += priorities[sameLetter];
	}
}

FindCommonInGroup();

output.innerHTML = sum;
